version: "3"
services:
#  db:
#    #image: "mysql:5.7"
#    image: "arm64v8/mysql"
#    container_name: pfdb
#    restart: unless-stopped
#    environment:
#      MYSQL_ROOT_PASSWORD: "root"
#    volumes:
#      - "./database:/docker-entrypoint-initdb.d"
#    ports:
#      - "3306:3306"

  app:
#    depends_on:
#      - db
    build: .
    restart: unless-stopped
    container_name: tc_apache
    ports:
      - "80:80"
    # Uncomment volumes section for development
    volumes:
      - "./:/app"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: pfdb
